### ISSUE TITLE
Hermes new flows

### ISSUE THREAD

**Issue by PrenSJ2** [tutorcruncher/hermes#262]
### New Deal Pipelines and stages

- On Boarders - associated Orgs can only have a status in `['pending_email_conf', 'trial_period', 'suspended']`
	- booked call - first time deal is created from a call booked (hermes)
	- unattended
	- on hold
	- post call no account
	- post call with account
	- signup - first time deal is created from a sigup (hermes)

- Paying - `paid_invoice_count` will move deal between stages
	- pay 0 - if `status==active & paid_invoice_count == null`
	- pay 1
	- pay 2
	- pay 3

-  Shadow (Realm) - if deals have been in other pipeline stage for x days without change then move them to associated shadow stage
	- terminated - if `status == terminated` move deal here
	- signup
	- booked call
	- unattended
	- post call with no account
	- pay 0
	- pay 1
	- pay 2
	- pay 3

### Action steps

- [ ] Match companies on email #248 
- [ ] Create and update deal with all custom fields that are on Org #131 
- [ ] Pass `has_signed_up` to pd  #260 
- [ ] Create deal in separate stage depending on if it came from booking a call or signing up #129 

### Extra Improvements

- [ ] `has_saved_card` and `trial_expiry_date` wanted custom fields #128 
- [ ] know how many sales and support calls are booked #131 
- [ ] Improve / fix bug with the Google calender meeting description #247 and #261
- [ ] varied callbooker availability hours per sales person (tony) #229
